### ISSUE TITLE
No d.ts files in package 

### ISSUE THREAD

**Issue by abhikmitra** [slicknode/graphql-query-complexity#10]
I don't see the d.ts files in the node module even though its written in TS. 
![image](https://user-images.githubusercontent.com/4750072/44943898-a8759c80-adeb-11e8-9038-486bbeb84d84.png)
What am I missing ?

**Comment by 19majkel94** [comment]
I think it's not yet published after switching codebase to TS.

**Comment by ivome** [comment]
d.ts files are now part of the package starting from version 0.2.0
