### ISSUE TITLE
Declaration merging

### ISSUE THREAD

**Issue by 19majkel94** [slicknode/graphql-query-complexity#11]
Since your library add new field to `GraphQLFieldConfig`, you should use the declaration and interfaces merging mechanism. This way users wouldn't be forced to replace it with `ComplexityGraphQLField` in their codebase, it will just work out of the box 🎉 

```ts
// `graphql.d.ts` file in your sources and package on npm

import { Complexity } from "graphql-query-complexity";

declare module "graphql/type/definition" {
  export interface GraphQLFieldConfig<TSource, TContext, TArgs = { [argName: string]: any }> {
    complexity?: Complexity;
  }
}
```

You should also expose this simple type to avoid repetition:
```ts
export type Complexity = number | ComplexityResolver;
```

**Comment by ivome** [comment]
I added declaration merging to the type definitions. This is available in version 0.2.0
