### ISSUE TITLE
Update to GraphQL-JS v14

### ISSUE THREAD

**Issue by 19majkel94** [slicknode/graphql-query-complexity#13]
Hi @ivome!

I've tried to update `graphql-query-complexity` to support `graphql-js` v14 but I got this error while running the tests: 
```
(...)
\graphql-query-complexity\node_modules\graphql\validation\validate.js:89
    throw new Error(errors.map(function (error) {
          ^
Error: Unknown directive "complexity".

Unknown directive "complexity".

Unknown directive "cost".

Unknown directive "complexity".

Unknown directive "complexity".

Unknown directive "complexity".
    at assertValidSDL 
(...)
```

Because v14 is making better validation of the schema/query:
https://github.com/graphql/graphql-js/releases/tag/v14.0.0

Can you take a look at your test suite and maybe update readme to add info about the demand of registering directives explicitly? 😕

**Comment by ivome** [comment]
Just upgraded the library to support graphql-js v14. New version is published on NPM

**Comment by 19majkel94** [comment]
Thanks! 🎉 
You could just add `|| ^0.14.0` to not making a breaking change as it's doesn't seem to be needed.

**Comment by ivome** [comment]
Done! 😉
