### ISSUE TITLE
Support `extensions` property

### ISSUE THREAD

**Issue by MichalLytek** [slicknode/graphql-query-complexity#19]
As `graphql-js` now has a dedicated mechanism for storing additional metadata, we should use that to place and read complexity info from constructed types:
https://github.com/graphql/graphql-js/pull/2097

**Comment by ivome** [comment]
This is great news... thanks for raising the issue! I added a new `fieldExtensionsEstimator` and added deprecation notices to the `fieldConfigEstimator` so we can remove this in future releases (plus those hacky TypeScript extensions of the GraphQL types we currently have).

**Comment by MichalLytek** [comment]
> those hacky TypeScript extensions of the GraphQL types we currently have

They are not so bad, it's better to provide typings for the properties because this will check the signature of function which results in better DX. However I haven't tried to merge declarations for `extenstions` as they might be types as record with any 😕

**Comment by ivome** [comment]
I just published a new version v0.4.0 with this feature
