### ISSUE TITLE
Support graphql v15

### ISSUE THREAD

**Issue by rigelglen** [slicknode/graphql-query-complexity#29]
Hi, graphql-query-complexity currently does not include graphql 15.0 as a supported peer depenency. Even though graphql 15 came with some breaking changes, I don't think anything needs to be changed to support it.

**Comment by rh389** [comment]
Unfortunately not that simple - this lib makes heavy use of `ValidationContext` which has a [breaking change ](https://github.com/graphql/graphql-js/pull/2130) for v15, no longer collecting its own errors. I'm looking into this now, but even with things naively patched up I'm seeing the tests failing, so I'm fairly certain this library will give the **wrong complexity results** with graphql 15.

**Comment by ivome** [comment]
There's already a PR #27 which addresses some issue with the ValidationContext. I haven't had time to look into this in detail yet. If someone wants to help with testing this and adding support for graphql v15, I'll be happy to review a PR.

**Comment by rh389** [comment]
The change to `ValidationContext` is easily dealt with but there's a bigger problem - [non-standard properties from field objects have been removed](https://github.com/graphql/graphql-js/pull/2117/files), which means `complexity` is no longer available on fields on the parsed schema.

I'm only just starting to dig into how this library works, but it appears this might be quite a tricky problem...

**Comment by ivome** [comment]
The `fieldConfigEstimator` and `legacyEstimator` have been deprecated for quite a while with console warnings. So I'd say we can drop support for those in the upcoming release since you can do the exact same thing with the `fieldExtensionEstimator` (or bake your own). 

If you want to create a PR for this, go ahead 👍

**Comment by rh389** [comment]
Great 👍 . PR now in: https://github.com/slicknode/graphql-query-complexity/pull/30

**Comment by ivome** [comment]
This is now support in v0.6.0
