### ISSUE TITLE
GraphQL Upload File not working with query complexity

### ISSUE THREAD

**Issue by lucaslimafons** [slicknode/graphql-query-complexity#39]
Hello everyone!
I'm using graphql query complexity in my project, but I got an error trying to upload a file

`[ValidationError: Argument "file" of required type "Upload!" was provided the variable "$file" which was not provided a runtime value.] {
  message: 'Argument "file" of required type "Upload!" was provided the variable "$file" which was not provided a runtime value.',
  locations: [ { line: 2, column: 16 } ],
  path: undefined,
  extensions: {
    code: 'GRAPHQL_VALIDATION_FAILED',
    exception: { stacktrace: [Array] }
  }
}
{
  stacktrace: [
    'GraphQLError: Argument "file" of required type "Upload!" was provided the variable "$file" which was not provided a runtime value.',
    '    at Object.getArgumentValues (project/node_modules/graphql/execution/values.js:176:17)',
    '    at project/node_modules/graphql-query-complexity/src/QueryComplexity.ts:236:24',
    '    at Array.reduce (<anonymous>)',
    '    at QueryComplexity.nodeComplexity (project/node_modules/graphql-query-complexity/src/QueryComplexity.ts:197:84)',
    '    at QueryComplexity.onOperationDefinitionEnter (project/node_modules/graphql-query-complexity/src/QueryComplexity.ts:146:33)',
    '    at Object.enter (project/node_modules/graphql/language/visitor.js:323:29)',
    '    at Object.enter (project/node_modules/graphql/utilities/TypeInfo.js:370:25)',
    '    at visit (project/node_modules/graphql/language/visitor.js:243:26)',
    '    at Object.validate (project/node_modules/graphql/validation/validate.js:69:24)',
    '    at validate (project/node_modules/apollo-server-core/src/requestPipeline.ts:510:14)'
  ]
}
POST /graphql 400 8.352 ms - 106`

It's pretty simple what I'm trying to do as we can see here:
![image](https://user-images.githubusercontent.com/5091837/106538832-a7c12300-64db-11eb-90d3-82d04bd189f7.png)

I've followed this tutorial + graphql-query-complexity

[https://dev.to/kingmaker9841/apollo-server-express-file-upload-on-local-storage-and-on-aws-s3-1km8](https://dev.to/kingmaker9841/apollo-server-express-file-upload-on-local-storage-and-on-aws-s3-1km8)

Did you already get this error?

**Comment by ivome** [comment]
Looks like you're not passing the file as a variable to the queryComplexity rule and therefore get the error message. Make sure to pass those values. 

```javascript
const app = express();
app.use('/api', graphqlHTTP(async (request, response, {variables}) => ({
  schema,
  validationRules: [
    queryComplexity({
      estimators: [
        // Configure your estimators
        simpleEstimator({defaultComplexity: 1})
      ],
      maximumComplexity: 1000,
      variables: {
         ...variables,
         // For multipart request, add the file objects here, from request object...
      },
      onComplete: (complexity: number) => {console.log('Query Complexity:', complexity);},
    })
  ]
})));
```

**Comment by ivome** [comment]
I'm closing this here as this is not related to this library, but rather how the input variables are passed to the validation rule...
