### ISSUE TITLE
Feature Request: expose the node to estimators

### ISSUE THREAD

**Issue by noc7c9** [slicknode/graphql-query-complexity#45]
Hiya, first off thanks for the amazing library. 

I'm trying to implement a custom estimation that depends on which fields are selected under a type.

Here's an example:
```graphql
query {
    a: someType { id } # Only id is selected, so calculation happens one way
    b: someType { id, some, fields } # More than id is selected so calculation happens another way
}
```

I don't believe that the exact behavior I want is achievable with `childComplexity` unfortunately, I need access to the selectionSet for the given node.

Hopefully that made some sense!

**Comment by ivome** [comment]
We could just pass the `node` as part of the estimator args. This would enable a whole bunch of additional functionality and ways to calculate the complexity of a field. Could potentially also be relevant for #41 

Happy to merge a PR if you want to add this.
