### ISSUE TITLE
API stability?

### ISSUE THREAD

**Issue by dburles** [slicknode/graphql-query-complexity#57]
Just wondering about the API stability as the package is still published as major version 0. Are there plans to release version 1.0.0? Thanks

**Comment by ivome** [comment]
The API is pretty stable now. There haven't been any breaking changes since version v0.6 (May 2020). I can publish the current version as v1.0.0 in the next few days to reflect that in the version number.

**Comment by dburles** [comment]
Thanks @ivome! Appreciate your effort on the package.
