### ISSUE TITLE
ApolloServer and Upload File

### ISSUE THREAD

**Issue by ahoys** [slicknode/graphql-query-complexity#59]
I'm having issues with integrating graphql-query-complexity to ApolloServer. Mainly because of multipart requests (sending images).

This is the error I encounter if I have createComplexityRule set and try to do a multipart:
`"message": "Argument \"file\" of required type \"Upload!\" was provided the variable \"$file\" which was not provided a runtime value.",`

![image](https://user-images.githubusercontent.com/14974945/133665396-ead44fd8-f430-4c20-8830-27ec6169b139.png)

And here is the request:
![image](https://user-images.githubusercontent.com/14974945/133664138-809cf716-6b05-46a7-ad52-ee55db24308d.png)
![image](https://user-images.githubusercontent.com/14974945/133664850-4030a1cf-1839-404e-8e23-06218d597833.png)

The code for the server:
```
const server = new ApolloServer({
    schema,
    validationRules: [
      depthLimit(4),
      createComplexityRule({
        maximumComplexity: 32,
        estimators: [simpleEstimator({ defaultComplexity: 1 })]
      }),
    ]
  });
```
How can I make multipart requests work with graphql-query-complexity + ApolloServer? Some of the closed issues seem to suggest using variables, but how can I do that with ApolloServer?

**Comment by ivome** [comment]
This has come up before and is not really related to this library, but rather how the variables are passed to the complexity rule. #39 Would be great if file uploads were standardized in GraphQL...

**Comment by ivome** [comment]
I'm gonna close this here as the files need to be passed as variables to the rule as outlined in this comment here https://github.com/slicknode/graphql-query-complexity/issues/39#issuecomment-771303341. In your example, this should probably happen somewhere in the `createComplexityRule` function.
