### ISSUE TITLE
Support grqphql.js version 16

### ISSUE THREAD

**Issue by sachaw** [slicknode/graphql-query-complexity#66]
v16 of graphql.js has been released with a number of breaking changes.

Most of the ecosystem is catching up fast and supporting it. As a number of widely used libs depend on this package, could you please look at adding support.
Here's the release notes:
https://github.com/graphql/graphql-js/releases

Regards.

**Comment by ivome** [comment]
I added support for GraphQL v16. This just landed in v0.11
