### ISSUE TITLE
Is there a way to assign complexities to mutations, objects and fields by default ?

### ISSUE THREAD

**Issue by bozvul993** [slicknode/graphql-query-complexity#74]
Is there a way to set up this library such that I provide a configuration where I specify the default cost for mutations, objects and fields ? Something like this:
`estimator({mutation: 100, object: 10, field: 1})`

This would be very useful for me and I saw it on another library that is not maintained. I cannot add custom directives on my schema and i cannot add extensions as well, because I am using apollo gateway.

**Comment by ivome** [comment]
You can just create a custom estimator where you examine the `type` that is being provided. If it's your mutation type, return `100` etc.
